---
title: "Data_cleaning_Edu"
author: "Xuejing"
date: "`r Sys.Date()`"
output: 
    html_document:
      number_sections: no
      theme: cerulean
      toc: yes
      toc_depth: 3
      toc_float:
        collapsed: false
      fontsize: 10pt
      code_folding: show
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```

```{r, load library, include=FALSE}
library(tidyverse)
library(lubridate)
library(vroom)
library(janitor)
library(skimr)
library(mice) 
library(VIM)
library(ggplot2)
library(gridExtra)
library(purrr)
library("GGally")

```

```{r, clean esg data}
ESG <- read_csv("ESG_data.csv")
ESG <- ESG %>% clean_names()
ESG <- pivot_longer(ESG,x1960_yr1960:x2020_yr2020,names_to = c("year","Year"),values_to = "amount",names_pattern = "x(.*)_yr(.*)")
ESG <- ESG %>% select(country_name,country_code,series_name,year,amount)

ESG_df <- ESG %>%
  pivot_wider(id_cols = c(country_name,country_code,year),names_from = series_name,values_from = amount,values_fn = max) %>% 
  clean_names() %>% 
  select(-c(country_name,country_code,year)) %>% 
  mutate_if(is.character,as.numeric)

ESG_index <- ESG %>%
  pivot_wider(id_cols = c(country_name,country_code,year),names_from = series_name,values_from = amount,values_fn = max) %>% 
  select(country_name,country_code,year)

ESG_index$year = as.Date(ISOdate(ESG_index$year, 1, 1),format = "%Y")

ESG_final <- cbind(ESG_index,ESG_df) %>% 
  filter(country_name %in% c("China","India","United States","United Kingdom","Spain","South Africa"))

write_csv(ESG_final,"ESG_final.csv")

```



```{r, clean edu data}
edu <- read_csv("edu_data.csv")
edu <- edu %>% clean_names()
edu <- pivot_longer(edu,x1970_yr1970:x2020_yr2020,names_to = c("year","Year"),values_to = "amount",names_pattern = "x(.*)_yr(.*)")
edu <- edu %>% select(country_name,country_code,series,year,amount)

edu_df <- edu %>%
  pivot_wider(id_cols = c(country_name,country_code,year),names_from = series,values_from = amount,values_fn = max) %>% 
  clean_names() %>% 
  select(-c(country_name,country_code,year)) %>% 
  mutate_if(is.character,as.numeric)

edu_index <- edu %>%
  pivot_wider(id_cols = c(country_name,country_code,year),names_from = series,values_from = amount,values_fn = max) %>% 
  select(country_name,country_code,year)
edu_index$year = as.Date(ISOdate(edu_index$year, 1, 1),format = "%Y")

edu_final <- cbind(edu_index,edu_df)
edu_final <- edu_final %>% filter(country_name %in% c("China","India","United States","United Kingdom","Spain","South Africa"))

write_csv(edu_final,"edu_final.csv")

```

```{r visualization}

p1 <- edu_final %>% filter(year>"1980-01-01") %>% ggplot(aes(x=year,y=gdp_per_capita_current_us,color=country_name))+
  geom_line()+
  theme_minimal()

p2 <- ESG_final %>% filter(year>"1980-01-01") %>% ggplot(aes(x=year,y=co2_emissions_metric_tons_per_capita,color=country_name))+
  geom_line()+
  theme_minimal()

grid.arrange(p1,p2,nrow = 2)

p3 <- edu_final %>% filter(year>"1990-01-01") %>% ggplot(aes(x=year,y=internet_users_per_100_people,color=country_name))+
  geom_line()+
  theme_minimal()

p4 <- edu_final %>% filter(year>"1990-01-01") %>% ggplot(aes(x=year,y=gross_enrolment_ratio_primary_gender_parity_index_gpi,color=country_name))+
  geom_line()+
  theme_minimal()

grid.arrange(p3,p4,nrow = 2)

```